#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: CommandLineTool

label: "Arriba - Gene fusion detection from RNA-seq"
doc: |
  Detect gene fusions from STAR-aligned BAM files. The input BAM must be
  generated by STAR with chimeric alignment parameters enabled
  (--chimSegmentMin 10 --chimOutType WithinBAM HardClip).

requirements:
  ResourceRequirement:
    coresMin: 1
    ramMin: 4096
  InlineJavascriptRequirement: {}

hints:
  DockerRequirement:
    dockerPull: "quay.io/biocontainers/arriba:2.5.1--h87b9561_0"

baseCommand: [arriba]

inputs:
  bam:
    type: File
    inputBinding:
      prefix: -x
    doc: "STAR-aligned BAM with chimeric reads (WithinBAM)"

  assembly:
    type: File
    inputBinding:
      prefix: -a
    doc: "Reference genome FASTA"

  gtf:
    type: File
    inputBinding:
      prefix: -g
    doc: "Gene annotation GTF"

  blacklist:
    type: File?
    inputBinding:
      prefix: -b
    doc: "Blacklist of recurrent artifacts (TSV, gzipped)"

  known_fusions:
    type: File?
    inputBinding:
      prefix: -k
    doc: "Known fusions for boosting sensitivity (TSV, gzipped)"

  protein_domains:
    type: File?
    inputBinding:
      prefix: -p
    doc: "Protein domain annotation (GFF3)"

  prefix:
    type: string
    doc: "Sample identifier for output naming"

arguments:
  - prefix: -o
    valueFrom: $(inputs.prefix)_fusions.tsv
  - prefix: -O
    valueFrom: $(inputs.prefix)_fusions.discarded.tsv
  - prefix: -f
    valueFrom: |
      ${
        if (inputs.blacklist) {
          return "";
        }
        return "blacklist";
      }

outputs:
  fusions:
    type: File
    outputBinding:
      glob: "*_fusions.tsv"
    doc: "Detected gene fusions"

  discarded_fusions:
    type: File
    outputBinding:
      glob: "*_fusions.discarded.tsv"
    doc: "Discarded fusion candidates (artifacts, low confidence)"
